### ISSUE TITLE
Fix documentation Signals Example

### ISSUE THREAD

**Issue by Nrosa01** [Extrys/LightWeightSignalBuses#4]
This is the documentation example that's not correct

```csharp
//The signal types
public struct SignalPlayerDamaged : ISignalPlayerHpChanged
{
    ISignalPlayerHpChanged.PlayerHp => playerHp;
    public float playerHp;
}
public struct SignalPlayerDamaged : ISignalPlayerHpChanged
{
    ISignalPlayerHpChanged.PlayerHp => playerHp;
    public float playerHp;
}

//The interface for the signals
public struct ISignalPlayerHpChanged
{
    float PlayerHp { get; }
}
```

This is the correct version that compiles

```csharp
//The interface for the signals
public interface ISignalPlayerHpChanged
{
    public float PlayerHp { get; }
}

//The signal types
public struct SignalPlayerDamaged : ISignalPlayerHpChanged
{
    public float playerHp;

    public float PlayerHp => playerHp;
}

public struct SignalPlayerHealed : ISignalPlayerHpChanged
{
    public float playerHp;

    public float PlayerHp => playerHp;
}
```

**Comment by Extrys** [comment]
what c# version are you using? technically Explicit Intefaces should work, maybe i just missed the float in front of those

**Comment by Extrys** [comment]
Fixed!

**Comment by Nrosa01** [comment]
This is still not fixed, I've tried .net 2.0 and .net 4x (.net framework) and both gave me these errors:
![Image](https://media.discordapp.net/attachments/808381067303190554/995730983938695330/unknown.png?width=854&height=408)
